# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liste < Formula
  desc "Tasks in markdown — a CLI for humans and AI agents"
  homepage "https://github.com/pufferhaus/liste"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.1/liste_1.1.1_darwin_amd64.tar.gz"
      sha256 "21e1db274000fcbc471b8271b7cfd4f4976d3633c603c1cb0621c130e1b881f9"

      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.1/liste_1.1.1_darwin_arm64.tar.gz"
      sha256 "09e7902a7b68ec7a810102eead023fb158c7eaac04b0369d00630632afe47dbe"

      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.1/liste_1.1.1_linux_amd64.tar.gz"
      sha256 "f564ad1457a894440ceb7f25b91051596f065f68e295cc532641d8d1f18e36c6"
      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pufferhaus/liste/releases/download/v1.1.1/liste_1.1.1_linux_arm64.tar.gz"
      sha256 "448b71f12a1d3e49df3559a15b7155adb1dad649b66beec8ff18ac52b68f0126"
      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  def caveats
    <<~EOS
      Install Claude Code skills for AI agents:
        liste skills install

      Then add to ~/.claude/CLAUDE.md:
        At the start of every session, invoke the liste:session-start skill.

      Docs: https://github.com/pufferhaus/liste
    EOS
  end

  test do
    system "#{bin}/liste", "version"
  end
end
