# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liste < Formula
  desc "Tasks in markdown — a CLI for humans and AI agents"
  homepage "https://github.com/mull-sys/liste"
  version "1.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mull-sys/liste/releases/download/v1.1.3/liste_1.1.3_darwin_amd64.tar.gz"
      sha256 "fcec584075b6a32051b9d8853eef5ea056c2a5e9bab8e93443febcbab33c7fc6"

      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mull-sys/liste/releases/download/v1.1.3/liste_1.1.3_darwin_arm64.tar.gz"
      sha256 "b86573b215f2d6aee2442f4a249f475333701802bf6972af6356dba24aab62e3"

      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mull-sys/liste/releases/download/v1.1.3/liste_1.1.3_linux_amd64.tar.gz"
      sha256 "dfceb879bfb28520ac85b9c543f0569bfbf2ebb2c20154c857639232d795275a"
      define_method(:install) do
        bin.install "liste"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mull-sys/liste/releases/download/v1.1.3/liste_1.1.3_linux_arm64.tar.gz"
      sha256 "f18a2d64dc9b6d60f6dec5c1e5e1573117ca6cf34e3354244b8f3bd27fbdf805"
      define_method(:install) do
        bin.install "liste"
      end
    end
  end

  def caveats
    <<~EOS
      Install Claude Code skills for AI agents:
        liste skills install

      Then add to ~/.claude/CLAUDE.md:
        At the start of every session, invoke the liste:session-start skill.

      Docs: https://github.com/mull-sys/liste
    EOS
  end

  test do
    system "#{bin}/liste", "version"
  end
end
